version: 2
updates:
  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dependencies listed in ui/package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
